{
 "title": "moon.__pair__",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"text-align:center; color:white; font-family: Andromeda; font-size: 800%\">moon __pair__</div>"
  },
  {
   "title": "Price",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(moon.__pair__.data.price)"
    },
    {
     "refCount": 1,
     "target": "alias(multiplySeries(moon.__pair__.data.price, #B), 'profit')"
    },
    {
     "refCount": 1,
     "target": "alias(multiplySeries(moon.__pair__.data.price, #C), 'loss')"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.data.volume)"
    }
   ]
  },
  {
   "title": "P & L",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.data.pandl.*)"
    }
   ]
  },
  {
   "title": "Sentiment score",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(moon.__pair__.data.sentiment.score)"
    }
   ]
  },
  {
   "title": "Tick direction score",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(moon.__pair__.data.tickDir.score)"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.memory.used.*)"
    }
   ]
  },
  {
   "title": "Process CPU %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.cpu.load.*)"
    }
   ]
  },
  {
   "title": "Disk usage %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.disk.used)"
    }
   ]
  },
  {
   "title": "Trade count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(moon.__pair__.data.myTradeCnt, 'Trade Count')"
    }
   ]
  },
  {
   "title": "(Re)starts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(moon.__pair__.process.restarts, A)"
    }
   ]
  }
 ]
}