{
 "title": "yabol.__pair__",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "2m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"text-align:center; color:white; font-family: Andromeda; font-size: 800%\">yabol __pair__</div>"
  },
  {
   "title": "Price",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(moon.__pair__.data.price)"
    },
    {
     "refCount": 1,
     "target": "alias(multiplySeries(moon.__pair__.data.price, #B), 'profit')"
    },
    {
     "refCount": 1,
     "target": "alias(multiplySeries(moon.__pair__.data.price, #C), 'loss')"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.data.volume)"
    }
   ]
  },
  {
   "title": "P & L",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.data.pandl.*)"
    }
   ]
  },
  {
   "title": "Sentiment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.data.price)"
    },
    {
     "refCount": 1,
     "target": "alias(multiplySeries(moon.__pair__.data.price, divideSeries(removeAboveValue(moon.__pair__.data.sentiment, 0), moon.__pair__.data.sentiment)), 'bear')"
    },
    {
     "refCount": 1,
     "target": "alias(multiplySeries(moon.__pair__.data.price, divideSeries(removeBelowValue(moon.__pair__.data.sentiment, 0), moon.__pair__.data.sentiment)), 'bull')"
    },
    {
     "target": "aliasByMetric(moon.__pair__.data.macdoverma.trendMa)"
    },
    {
     "target": "alias(moon.__pair__.data.macdoverma2.trendMa, trendMa2)"
    }
   ]
  },
  {
   "title": "MACD over MA",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.data.macdoverma.macd)"
    },
    {
     "target": "aliasByMetric(moon.__pair__.data.macdoverma.signal)"
    },
    {
     "target": "alias(removeBelowValue(moon.__pair__.data.macdoverma.histogram, 0), 'histogram_pos')"
    },
    {
     "target": "alias(removeAboveValue(moon.__pair__.data.macdoverma.histogram, 0), 'histogram_neg')"
    },
    {
     "refCount": 1,
     "target": "alias(multiplySeries(moon.__pair__.data.macdoverma.histogram, divideSeries(removeAboveValue(moon.__pair__.data.macdoverma.sentiment, 0), moon.__pair__.data.macdoverma.sentiment)), 'bear')"
    },
    {
     "refCount": 1,
     "target": "alias(multiplySeries(moon.__pair__.data.macdoverma.histogram, divideSeries(removeBelowValue(moon.__pair__.data.macdoverma.sentiment, 0), moon.__pair__.data.macdoverma.sentiment)), 'bull')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.memory.used.jvm)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.cpu.load.*)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(moon.__pair__.disk.used)"
    }
   ]
  },
  {
   "title": "Trade count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(moon.__pair__.data.myTradeCnt, 'Trade Count')"
    }
   ]
  },
  {
   "title": "(Re)starts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(moon.__pair__.process.restarts, A)"
    }
   ]
  }
 ]
}